name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup sbt
      uses: sbt/setup-sbt@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 21
    - run: sbt scripted
